#!/bin/bash
# init-slave.sh -- WAL streaming replication setup
# Runs once on first startup of the slave container (empty PGDATA)

echo "==> [slave] Starting replication setup from ${PRIMARY_HOST}:${PRIMARY_PORT}"

export PGPASSWORD=$(cat /run/secrets/replication_password | tr -d '\n\r')

# Wait for master to be ready
until pg_isready -h "${PRIMARY_HOST}" -p "${PRIMARY_PORT}" -U "${REPLICATION_USER}"; do
  echo "==> [slave] Master not ready, retrying in 3s..."
  sleep 3
done

echo "==> [slave] Master ready. Running pg_basebackup..."

# Clear PGDATA initialized by docker-entrypoint (incompatible with pg_basebackup)
rm -rf "${PGDATA:?}"/*

# Copy all data from master (-R generates standby.signal + primary_conninfo)
pg_basebackup \
  -h "${PRIMARY_HOST}" \
  -p "${PRIMARY_PORT}" \
  -U "${REPLICATION_USER}" \
  -D "${PGDATA}" \
  -Xs \
  -P \
  -R

echo "==> [slave] pg_basebackup done. Creating replication slot on master..."

# Create named replication slot on master
# -d postgres is required: connect to 'postgres' db, not 'replicator' (which is a user, not a db)
psql \
  -h "${PRIMARY_HOST}" \
  -p "${PRIMARY_PORT}" \
  -U "${REPLICATION_USER}" \
  -d postgres \
  -c "SELECT pg_create_physical_replication_slot('slave_slot', true);" \
  && echo "==> [slave] Slot created." \
  || echo "==> [slave] Slot may already exist, continuing."

# Add slot name to auto.conf (generated by pg_basebackup -R)
echo "primary_slot_name = 'slave_slot'" >> "${PGDATA}/postgresql.auto.conf"

unset PGPASSWORD
echo "==> [slave] Init complete. Starting in standby mode."
