# =============================================================================
# pg_hba.conf  Nud Slave (standby coordinator Citus)
# Identique au Master : le Slave peut tre promu  tout moment,
# il doit donc avoir les mmes rgles d'accs que le Master.
# =============================================================================

local   all             all                                     trust

host    all             all             172.16.0.0/12           scram-sha-256
host    all             all             10.0.0.0/8              scram-sha-256

host    replication     replicator      172.16.0.0/12           scram-sha-256
host    replication     replicator      10.0.0.0/8              scram-sha-256

host    all             all             127.0.0.1/32            scram-sha-256
